version: '3'
services:
  db:
     image: mysql
     container_name: mysql_db
     restart: always
     environment:
        - MYSQL_ROOT_PASSWORD="secret"
  web:
    image: apache
    build: ./webapp1
    depends_on:
       - db
    container_name: apache_web
    restart: always
    ports:
      - "9090:80"

